import Provider from "./provider";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "./ConvexClientProvider";
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className="h-full w-full">
        <head>
          <link rel="icon" type="image/svg+xml" href="/vercel.svg" />
        </head>
      <body className="min-h-screen w-full bg-orange-100 text-black overflow-x-hidden">
        <ConvexClientProvider>
          <Provider>
            <main className="min-h-screen w-full">
              {children}
            </main>
            <Toaster />
          </Provider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
